name: Hello Agile 

on: 
  push: 
    branches: [ dev ] 
  pull_request: 
    branches: [ main ] # Triggers when a PR is opened targeting 'main' 
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello from GitHub Actions!"

#this is a small comment